### ISSUE TITLE
Compatibility with mkdocstrings

### ISSUE THREAD

**Issue by arabnejad** [timvink/mkdocs-enumerate-headings-plugin#26] opened 2021-05-10 12:44 UTC
Hi

I am getting this error when I used `enumerate-headings` with `mkdocstrings`

```sh
INFO    -  Cleaning site directory 
Traceback (most recent call last):
  File "/home/hamid/.local/bin/mkdocs", line 8, in <module>
    sys.exit(cli())
  File "/home/hamid/.local/lib/python3.8/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/home/hamid/.local/lib/python3.8/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/home/hamid/.local/lib/python3.8/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/hamid/.local/lib/python3.8/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/hamid/.local/lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/home/hamid/.local/lib/python3.8/site-packages/mkdocs/__main__.py", line 133, in serve_command
    serve.serve(
  File "/home/hamid/.local/lib/python3.8/site-packages/mkdocs/commands/serve.py", line 141, in serve
    config = builder()
  File "/home/hamid/.local/lib/python3.8/site-packages/mkdocs/commands/serve.py", line 136, in builder
    build(config, live_server=live_server, dirty=dirty)
  File "/home/hamid/.local/lib/python3.8/site-packages/mkdocs/commands/build.py", line 266, in build
    nav = config['plugins'].run_event('nav', nav, config=config, files=files)
  File "/home/hamid/.local/lib/python3.8/site-packages/mkdocs/plugins.py", line 94, in run_event
    result = method(item, **kwargs)
  File "/home/hamid/.local/lib/python3.8/site-packages/mkdocs_enumerate_headings_plugin/plugin.py", line 97, in on_nav
    page.render(config, files)
  File "/home/hamid/.local/lib/python3.8/site-packages/mkdocs/structure/pages.py", line 175, in render
    self.content = md.convert(self.markdown)
  File "/home/hamid/.local/lib/python3.8/site-packages/markdown/core.py", line 264, in convert
    root = self.parser.parseDocument(self.lines).getroot()
  File "/home/hamid/.local/lib/python3.8/site-packages/markdown/blockparser.py", line 90, in parseDocument
    self.parseChunk(self.root, '\n'.join(lines))
  File "/home/hamid/.local/lib/python3.8/site-packages/markdown/blockparser.py", line 105, in parseChunk
    self.parseBlocks(parent, text.split('\n\n'))
  File "/home/hamid/.local/lib/python3.8/site-packages/markdown/blockparser.py", line 123, in parseBlocks
    if processor.run(parent, blocks) is not False:
  File "/home/hamid/.local/lib/python3.8/site-packages/mkdocstrings/extension.py", line 120, in run
    html, headings = self._process_block(identifier, block, heading_level)
  File "/home/hamid/.local/lib/python3.8/site-packages/mkdocstrings/extension.py", line 153, in _process_block
    config = yaml.safe_load(yaml_block) or {}
  File "/home/hamid/.local/lib/python3.8/site-packages/yaml/__init__.py", line 162, in safe_load
    return load(stream, SafeLoader)
  File "/home/hamid/.local/lib/python3.8/site-packages/yaml/__init__.py", line 114, in load
    return loader.get_single_data()
  File "/home/hamid/.local/lib/python3.8/site-packages/yaml/constructor.py", line 51, in get_single_data
    return self.construct_document(node)
  File "/home/hamid/.local/lib/python3.8/site-packages/yaml/constructor.py", line 60, in construct_document
    for dummy in generator:
  File "/home/hamid/.local/lib/python3.8/site-packages/yaml/constructor.py", line 413, in construct_yaml_map
    value = self.construct_mapping(node)
  File "/home/hamid/.local/lib/python3.8/site-packages/yaml/constructor.py", line 218, in construct_mapping
    return super().construct_mapping(node, deep=deep)
  File "/home/hamid/.local/lib/python3.8/site-packages/yaml/constructor.py", line 141, in construct_mapping
    raise ConstructorError("while constructing a mapping", node.start_mark,
yaml.constructor.ConstructorError: while constructing a mapping
  in "<unicode string>", line 7, column 18:
            members: {{ funcs_workflow }}   
                     ^
found unhashable key
  in "<unicode string>", line 7, column 19:
            members: {{ funcs_workflow }}   
                      ^
```

**Comment by arabnejad** [comment] 2021-05-25 15:03
Hi @timvink 

thanks for your reply,
about `requirements.txt` , I already have another one specific for mkdocs in : https://github.com/arabnejad/flee/blob/master/docs/mkdocs-requirements.txt 
and those py packages are installed in `readthedocs.yml` and before calling `mkdocs gh-deploy --force`

I think if you enable that option again ,  https://github.com/arabnejad/flee/blob/c7901e2a0de70f18c3267236e127ab1c26c8f5e5/mkdocs.yml#L76, you will see the error

**Comment by arabnejad** [comment] 2021-05-25 15:04
Hi @timvink 

thanks for your reply,
about `requirements.txt` , I already have another one specific for mkdocs in : https://github.com/arabnejad/flee/blob/master/docs/mkdocs-requirements.txt 
and those py packages are installed in `readthedocs.yml` and before calling `mkdocs gh-deploy --force`

I think if you enable that option again ,  https://github.com/arabnejad/flee/blob/c7901e2a0de70f18c3267236e127ab1c26c8f5e5/mkdocs.yml#L76, you will see the error

**Comment by timvink** [comment] 2021-05-26 11:38
I did enable that option again, and I did not get an error. So I'm not able to reproduce this error.

Can you try updating to the latest versions of related package & see if you still get the error?

**Comment by timvink** [comment] 2021-06-18 13:43
Closing as issue cannot be reproduced.

**Closed by timvink** 2021-06-18 13:43 UTC
Labels: question
